games:
  - id: elden-ring
    rawg_id: 326243
    nom: "Elden Ring"
    plateformes: [PS5, PS4, Xbox Series, Xbox One, PC]
    sources:
      - "fr.bandainamcoent.eu/elden-ring/elden-ring/elden-ring-wiki"
      - "jeuxvideo.com/wikis-soluce-astuces/1062487/wiki-de-elden-ring.htm"
      - "jeuxvideo.fr/guide-jeu/410523-elden-ring-notre-guide-pour-bien-debuter"
    statut: actif

  - id: skyrim
    rawg_id: 5679
    nom: "The Elder Scrolls V: Skyrim"
    plateformes: [PS5, PS4, Xbox Series, Xbox One, PC, Switch]
    sources:
      - "elderscrolls.fandom.com/fr/wiki/Wiki_The_Elder_Scrolls/Portail/Skyrim"
      - "jeuxvideo.com/wikis-soluce-astuces/345589/wiki-de-the-elder-scrolls-v-skyrim.htm"
    statut: actif